let list = [
 /* "FFA",
  "2TDM Mothership",
  //"2TTW",
  "2TDM Domination",
  "2TDM",
  "4TDM",
  //"2TTW",
  "4TDM Domination",
  "2TDM Mothership",
  "Open 3TDM Maze",
  "4TDM",
  "Open 4TDM Maze",
  //"2TTW",
  "4TDM Map 2",
  "2TDM Domination",
  "Soccer",
  "2TDM Map 2",
  "4TDM Domination",
  "2TDM Map 2",
  "2TDM Map 2",
  //"2TTW",
  "4TDM Domination",
  "2TDM Mothership",
  "FFA",
  "Open 4TDM Maze",
  "Maze",
  "2TDM Domination",
  "Open 2TDM Maze",
  "3TDM Domination",*/
  "Developer",
  "Developer",
  "Developer",
  "Developer",
  "Developer",
  "Developer",
  "Developer",
  "Developer",
  "Developer",
  "Developer"
];
let config = {
  "FFA": {
    NAME: "FFA",
    WIDTH: 4250,
    HEIGHT: 4250,
    RANDOM_COLORS: true,
    X_GRID: 12,
    Y_GRID: 12,
    BOTS: 5,
    MAX_FOOD: 50,
    ROOM_SETUP: [
      [ "obsr", "obsr", "obsr", "obsr", "arc2", "obsr", "roid", "obsr", "obsr", "obsr", "obsr", "arcl" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "rock", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "rock", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "norm" ],
      [ "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "norm" ],
      [ "roid", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "roid" ],
      [ "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "norm" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "rock", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "rock", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "arc2", "obsr", "roid", "obsr", "obsr", "obsr", "obsr", "arcl" ]
    ],
  },
  "2TDM": {
    NAME: "2TDM",
    WIDTH: 6000,
    HEIGHT: 6000,
    X_GRID: 9,
    Y_GRID: 9,
    BOTS: 5,
    MAX_FOOD: 50,
    TEAMS: 2,
    ROOM_SETUP: [
      ["bas1", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "bas2"],
      ["bap1", "arcl", "obsr", "obsr", "arc2", "obsr", "obsr", "arcl", "bap2"],
      ["bas1", "obsr", "obsr", "obsr", "roid", "obsr", "obsr", "obsr", "bas2"],
      ["bap1", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "bap2"],
      ["bas1", "arc2", "roid", "nest", "nest", "nest", "roid", "arc2", "bas2"],
      ["bap1", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "bap2"],
      ["bas1", "obsr", "obsr", "obsr", "roid", "obsr", "obsr", "obsr", "bas2"],
      ["bap1", "arcl", "obsr", "obsr", "arc2", "obsr", "obsr", "arcl", "bap2"],
      ["bas1", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "bas2"],
    ]
  },
  "2TTW": {
    NAME: "2TTW",
    WIDTH: 6000,
    HEIGHT: 6000,
    X_GRID: 9,
    Y_GRID: 9,
    BOTS: 5,
    MAX_FOOD: 50,
    TEAMS: 2,
    ROOM_SETUP: [
      ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
      ["norm", "arcl", "norm", "norm", "norm", "norm", "norm", "arcl", "norm"],
      ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
      ["norm", "norm", "norm", "nest", "nest", "nest", "norm", "norm", "norm"],
      ["norm", "arc2", "norm", "nest", "nest", "nest", "norm", "arc2", "norm"],
      ["norm", "norm", "norm", "nest", "nest", "nest", "norm", "norm", "norm"],
      ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
      ["norm", "arcl", "norm", "norm", "arc2", "norm", "norm", "arcl", "norm"],
      ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ]
  },
  "2TDM Map 2": {
    NAME: "2TDM",
    WIDTH: 6000,
    HEIGHT: 6000,
    X_GRID: 9,
    Y_GRID: 9,
    BOTS: 5,
    MAX_FOOD: 50,
    TEAMS: 2,
    ROOM_SETUP: [
      ["bas1", "bap1", "bas1", "bap1", "bas1", "bap1", "bas1", "bap1", "bas1"],
      ["obsr", "arcl", "obsr", "obsr", "arc2", "obsr", "obsr", "arcl", "obsr"],
      ["obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr"],
      ["obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr"],
      ["obsr", "arc2", "obsr", "nest", "nest", "nest", "obsr", "arc2", "obsr"],
      ["obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr"],
      ["obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr"],
      ["obsr", "arcl", "obsr", "obsr", "arc2", "obsr", "obsr", "arcl", "obsr"],
      ["bas2", "bap2", "bas2", "bap2", "bas2", "bap2", "bas2", "bap2", "bas2"],
    ]
  },
  "3TDM": {
    NAME: "3TDM",
    WIDTH: 6000,
    HEIGHT: 6000,
    X_GRID: 9,
    Y_GRID: 9,
    BOTS: 5,
    MAX_FOOD: 50,
    TEAMS: 3,
    ROOM_SETUP: [
      ["obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr"],
      ["obsr", "arc2", "obsr", "obsr", "arcl", "obsr", "obsr", "arc2", "obsr"],
      ["obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr"],
      ["obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr"],
      ["bas1", "arcl", "obsr", "nest", "nest", "nest", "obsr", "arcl", "bas2"],
      ["obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr"],
      ["obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr"],
      ["obsr", "arc2", "obsr", "obsr", "arcl", "obsr", "obsr", "arc2", "obsr"],
      ["obsr", "obsr", "obsr", "obsr", "bas3", "obsr", "obsr", "obsr", "obsr"],
    ]
  },
  "4TDM": {
    NAME: "4TDM",
    WIDTH: 6000,
    HEIGHT: 6000,
    X_GRID: 9,
    Y_GRID: 9,
    BOTS: 5,
    MAX_FOOD: 50,
    TEAMS: 4,
    ROOM_SETUP: [
      ["roid", "obsr", "obsr", "obsr", "bas4", "obsr", "obsr", "obsr", "roid"],
      ["obsr", "arc2", "obsr", "obsr", "arcl", "obsr", "obsr", "arc2", "obsr"],
      ["obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr"],
      ["obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr"],
      ["bas1", "arcl", "obsr", "nest", "nest", "nest", "obsr", "arcl", "bas2"],
      ["obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr"],
      ["obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr"],
      ["obsr", "arc2", "obsr", "obsr", "arcl", "obsr", "obsr", "arc2", "obsr"],
      ["roid", "obsr", "obsr", "obsr", "bas3", "obsr", "obsr", "obsr", "roid"],
    ]
  },
  "4TDM Map 2": {
    NAME: "4TDM",
    WIDTH: 6000,
    HEIGHT: 6000,
    X_GRID: 9,
    Y_GRID: 9,
    BOTS: 5,
    MAX_FOOD: 50,
    TEAMS: 4,
    ROOM_SETUP: [
      ["roid", "obsr", "obsr", "obsr", "bas2", "obsr", "obsr", "obsr", "roid"],
      ["obsr", "arc2", "obsr", "obsr", "arcl", "obsr", "obsr", "arc2", "obsr"],
      ["obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr"],
      ["obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr"],
      ["bas4", "arcl", "obsr", "nest", "nest", "nest", "obsr", "arcl", "bas3"],
      ["obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr"],
      ["obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr"],
      ["obsr", "arc2", "obsr", "obsr", "arcl", "obsr", "obsr", "arc2", "obsr"],
      ["roid", "obsr", "obsr", "obsr", "bas1", "obsr", "obsr", "obsr", "roid"],
    ]
  },
  "3TDM Domination": {
    NAME: "3TDM Domination",
    WIDTH: 5550,
    HEIGHT: 5550,
    X_GRID: 15,
    Y_GRID: 15,
    NUMBER_OF_DOMS: 4,
    BOTS: 5,
    MAX_FOOD: 50,
    TEAMS: 3,
    ROOM_SETUP: [
      [ "bas1", "bap1", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm" ],
      [ "bap1", "bap1", "norm", "norm", "norm", "norm", "norm", "arcl", "norm", "norm", "norm", "norm", "norm", "norm", "norm" ],
      [ "norm", "norm", "norm", "norm", "norm", "norm", "norm", "domN", "norm", "norm", "norm", "norm", "norm", "norm", "norm" ],
      [ "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm" ],
      [ "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm" ],
      [ "norm", "norm", "norm", "norm", "norm", "norm", "norm", "arc2", "norm", "norm", "norm", "norm", "norm", "norm", "norm" ],
      [ "norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "norm", "norm", "norm", "norm", "norm", "norm" ],
      [ "norm", "arcl", "domW", "norm", "norm", "arc2", "nest", "domC", "nest", "arc2", "norm", "norm", "domE", "arcl", "norm" ],
      [ "norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "norm", "norm", "norm", "norm", "norm", "norm" ],
      [ "norm", "norm", "norm", "norm", "norm", "norm", "norm", "arc2", "norm", "norm", "norm", "norm", "norm", "norm", "norm" ],
      [ "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm" ],
      [ "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm" ],
      [ "norm", "norm", "norm", "norm", "norm", "norm", "norm", "domS", "norm", "norm", "norm", "norm", "norm", "norm", "norm" ],
      [ "bap3", "bap3", "norm", "norm", "norm", "norm", "norm", "arcl", "norm", "norm", "norm", "norm", "norm", "bap2", "bap2" ],
      [ "bas3", "bap3", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "bap2", "bas2" ]
    ],
  },
  "2TDM Domination": {
    NAME: "2TDM Domination",
    WIDTH: 5550,
    HEIGHT: 5550,
    X_GRID: 15,
    Y_GRID: 15,
    NUMBER_OF_DOMS: 5,
    BOTS: 5,
    MAX_FOOD: 50,
    TEAMS: 2,
    ROOM_SETUP: [
      [ "bas1", "bap1", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "bap1", "bap1", "obsr", "obsr", "obsr", "obsr", "obsr", "arcl", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "domN", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arc2", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "arcl", "domW", "obsr", "obsr", "arc2", "nest", "domC", "nest", "arc2", "obsr", "obsr", "domE", "arcl", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arc2", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "domS", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arcl", "obsr", "obsr", "obsr", "obsr", "obsr", "bap2", "bap2" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "bap2", "bas2" ]
    ],
  },
  "4TDM Domination": {
    NAME: "4TDM Domination",
    WIDTH: 5550,
    HEIGHT: 5550,
    X_GRID: 15,
    Y_GRID: 15,
    NUMBER_OF_DOMS: 3,
    BOTS: 5,
    MAX_FOOD: 50,
    TEAMS: 4,
    ROOM_SETUP: [
      [ "bas1", "bap1", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "bap4", "bas4" ],
      [ "bap1", "bap1", "obsr", "obsr", "obsr", "obsr", "obsr", "arcl", "obsr", "obsr", "obsr", "obsr", "obsr", "bap4", "bap4" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "domN", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arc2", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "arcl", "domW", "obsr", "obsr", "arc2", "nest", "domC", "nest", "arc2", "obsr", "obsr", "domE", "arcl", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arc2", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "domS", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "bap3", "bap3", "obsr", "obsr", "obsr", "obsr", "obsr", "arcl", "obsr", "obsr", "obsr", "obsr", "obsr", "bap2", "bap2" ],
      [ "bas3", "bap3", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "bap2", "bas2" ]
    ],
  },
  "Maze": {
    NAME: "Maze",
    WIDTH: 5000,
    HEIGHT: 5000,
    X_GRID: 15,
    Y_GRID: 15,
    BOTS: 5,
    MAZE: 32,
    MAX_FOOD: 3,
    ROOM_SETUP: [
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arcl", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "domN", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arc2", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "arcl", "domW", "obsr", "obsr", "arc2", "nest", "domC", "nest", "arc2", "obsr", "obsr", "domE", "arcl", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arc2", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "domS", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arcl", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ]
    ],
  },
  "Open 2TDM Maze": {
    NAME: "Open 2TDM Maze",
    WIDTH: 5000,
    HEIGHT: 5000,
    X_GRID: 15,
    Y_GRID: 15,
    BOTS: 5,
    MAZE: 32,
    TEAMS: 2,
    MAX_FOOD: 3,
    ROOM_SETUP: [
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arcl", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "domN", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arc2", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "arcl", "domW", "obsr", "obsr", "arc2", "nest", "domC", "nest", "arc2", "obsr", "obsr", "domE", "arcl", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arc2", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "domS", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arcl", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ]
    ],
  },
  "Open 3TDM Maze": {
    NAME: "Open 3TDM Maze",
    WIDTH: 5000,
    HEIGHT: 5000,
    X_GRID: 15,
    Y_GRID: 15,
    BOTS: 5,
    MAZE: 32,
    TEAMS: 3,
    MAX_FOOD: 3,
    ROOM_SETUP: [
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arcl", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "domN", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arc2", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "arcl", "domW", "obsr", "obsr", "arc2", "nest", "domC", "nest", "arc2", "obsr", "obsr", "domE", "arcl", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arc2", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "domS", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arcl", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ]
    ],
  },
  "Open 4TDM Maze": {
    NAME: "Open 4TDM Maze",
    WIDTH: 5000,
    HEIGHT: 5000,
    X_GRID: 15,
    Y_GRID: 15,
    BOTS: 5,
    MAZE: 32,
    TEAMS: 4,
    MAX_FOOD: 3,
    ROOM_SETUP: [
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arcl", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "domN", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arc2", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "arcl", "domW", "obsr", "obsr", "arc2", "nest", "domC", "nest", "arc2", "obsr", "obsr", "domE", "arcl", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arc2", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "domS", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "arcl", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ]
    ],
  },
  "2TDM Mothership": {
    NAME: "2TDM Mothership",
    WIDTH: 4000,
    MOTHERSHIP_LOOP: true,
    HEIGHT: 4000,
    X_GRID: 12,
    Y_GRID: 12,
    MODE: 'tdm',
    TEAMS: 2,
    BOTS: 5,
    MAX_FOOD: 3,
    ROOM_SETUP: [
      [ "arcl", "obsr", "obsr", "obsr", "arc2", "obsr", "roid", "obsr", "obsr", "obsr", "obsr", "arcl" ],
      [ "obsr", "mot1", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "rock", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "rock", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "nest", "nest", "nest", "nest", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "nest", "nest", "nest", "nest", "obsr", "obsr", "obsr", "obsr" ],
      [ "roid", "obsr", "obsr", "obsr", "nest", "nest", "nest", "nest", "obsr", "obsr", "obsr", "roid" ],
      [ "obsr", "obsr", "obsr", "obsr", "nest", "nest", "nest", "nest", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr" ],
      [ "obsr", "obsr", "rock", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "rock", "obsr", "obsr" ],
      [ "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "obsr", "mot2", "obsr" ],
      [ "arcl", "obsr", "obsr", "obsr", "obsr", "obsr", "roid", "arc2", "obsr", "obsr", "obsr", "arcl" ]
    ],
  },
  "4TDM Mothership": {
    NAME: "4TDM Mothership",
    WIDTH: 4000,
    HEIGHT: 4000,
    X_GRID: 12,
    Y_GRID: 12,
    MODE: 'tdm',
    TEAMS: 4,
    BOTS: 5,
    MAX_FOOD: 3,
    ROOM_SETUP: [
      [ "norm", "norm", "norm", "norm", "norm", "norm", "roid", "norm", "norm", "norm", "norm", "norm" ],
      [ "norm", "mot1", "arcl", "norm", "arcl", "norm", "arcl", "norm", "arcl", "norm", "mot3", "norm" ],
      [ "norm", "arcl", "rock", "norm", "norm", "norm", "norm", "norm", "norm", "rock", "arcl", "norm" ],
      [ "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm" ],
      [ "norm", "arcl", "norm", "norm", "nest", "nest", "nest", "nest", "norm", "norm", "arcl", "norm" ],
      [ "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "norm" ],
      [ "roid", "arcl", "norm", "norm", "nest", "nest", "nest", "nest", "norm", "norm", "arcl", "roid" ],
      [ "norm", "norm", "norm", "norm", "nest", "nest", "nest", "nest", "norm", "norm", "norm", "norm" ],
      [ "norm", "arcl", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "arcl", "norm" ],
      [ "norm", "norm", "rock", "norm", "norm", "norm", "norm", "norm", "norm", "rock", "norm", "norm" ],
      [ "norm", "mot4", "arcl", "norm", "arcl", "norm", "arcl", "norm", "arcl", "norm", "mot2", "norm" ],
      [ "norm", "norm", "norm", "norm", "norm", "norm", "roid", "norm", "norm", "norm", "norm", "norm" ]
    ]
  },
  "Developer": {
    NAME: "Dev Server",
    WIDTH: 4000,
    HEIGHT: 4000,
    X_GRID: 15,
    Y_GRID: 15,
    BOTS: 0,
    MAX_FOOD: 50,
    TESTING: false,
    ROOM_SETUP: [
    ["roid", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "roid"],
    ["norm", "arcl", "norm", "arc2", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "arc2", "norm", "arcl", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "arc2", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "arc2", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "nest", "nest", "norm", "nest", "nest", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "arc2", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "arc2", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "arcl", "norm", "arc2", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "arc2", "norm", "arcl", "norm"],
    ["roid", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "roid"]
  ],
  },
   "Soccer": {
    NAME: "Soccer",
    WIDTH: 4000,
    HEIGHT: 4000,
    X_GRID: 11,
    Y_GRID: 11,
    BOTS: 2,
    MAX_FOOD: 50,
    TEAMS: 2,
    ROOM_SETUP: [
      [ "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall" ],
      [ "wall", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "wall" ],
      [ "wall", "nest", "obsr", "arc2", "obsr", "nest", "obsr", "arc2", "obsr", "nest", "wall" ],
      [ "wall", "wall", "obsr", "obsr", "obsr", "nest", "obsr", "obsr", "obsr", "wall", "wall" ],
      [ "bap1", "obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr", "bap2" ],
      [ "bas1", "arcl", "obsr", "arcl", "nest", "ball", "nest", "arcl", "obsr", "arcl", "bas2" ],
      [ "bap1", "obsr", "obsr", "obsr", "nest", "nest", "nest", "obsr", "obsr", "obsr", "bap2" ],
      [ "wall", "wall", "obsr", "obsr", "obsr", "nest", "obsr", "obsr", "obsr", "wall", "wall" ],
      [ "wall", "nest", "obsr", "arc2", "obsr", "nest", "obsr", "arc2", "obsr", "nest", "wall" ],
      [ "wall", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "nest", "wall" ],
      [ "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall" ]
    ],
  },
};

exports.output = {
  "host": "0.0.0.0",
  "servesStatic": true,
  "port": 3000,
  "logpath": "logger.php",
  "networkUpdateFactor": 24,
  "socketWarningLimit": 5,
  "networkFrontlog": 1,
  "networkFallbackTime": 150,
  "visibleListInterval": 1000,
  "gameSpeed": 1,
  "runSpeed": 1.5,
  "maxHeartbeatInterval": 30000,
  "sqlinfo":{
    "connectionLimit": 50,
    "host": "DEFAULT",
    "user": "root",
    "password": "DEFAULT",
    "database": "DEFAULT",
    "debug": false
  },
  "verbose": true,
  "WIDTH": 3250,
  "HEIGHT": 3250,
  "MODE": "ffa",
  "RANDOM_COLORS": false,
  "TEAMS": 0,
  "BANNED_CHARACTER_REGEX": "/[\uFDFD\u200E\u0000]/gi",
  "ROOM_SETUP": [
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "nest", "nest", "norm", "nest", "nest", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"],
    ["norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm"]
  ],
  "X_GRID": 9,
  "Y_GRID": 9,
  "DAMAGE_CONSTANT": 0.6,
  "KNOCKBACK_CONSTANT": 1,
  "ROOM_BOUND_FORCE": 0.01,
  "TEAMS": 0,
  "MAZE": false,
  "FOOD": [
    0,
    0.75,
    0.22,
    0.1,
    0.005,
    0,
    0
  ],
  "FOOD_NEST": [
    0,
    0.0,
    0.0,
    0.75,
    0.23,
    0.02,
    0
  ],
  "MAX_SKILL": 9,
  "SOFT_MAX_SKILL": 0.59,
  "TIER_1": 15,
  "TIER_2": 30,
  "TIER_3": 45,
  "SKILL_CAP": 45,
  "SKILL_SOFT_CAP": 0,
  "SKILL_CHEAT_CAP": 45,
  "SKILL_LEAK": 0,
  "STEALTH": 4,
  "MIN_SPEED": 0.001,
  "FOOD_AMOUNT": 0.001,
  "SKILL_BOOST": 5,
  "BOTS": 2,
  "GLASS_HEALTH_FACTOR": 2,
  "TOKEN_REQUIRED": false
};

const rand = require("../random.js");
let mode = list[rand.chooseChance(2, 2, 1, 1, 2, 3, 3)];
if (!config[mode]) throw new Error("That gamemode does not exist!");
for (let key in config[mode]) exports.output[key] = config[mode][key];
if (config[mode].TEAMS) exports.output.MODE = "tdm";
console.log(mode);